SELECT a.ID, a.LASTNAME, a.FIRSTNAME, a.SECONDNAME, a.BIRTHDAY, ss.CHEMISTRY_COURSE, ss.INFORMATICS_COURSE, ss.PHYSICS_COURSE
FROM sum_scores ss JOIN APPLICANT a ON ss.APP_ID = a.ID WHERE APP_ID = 5;

SELECT a.ID, a.LASTNAME, a.FIRSTNAME, a.SECONDNAME, a.BIRTHDAY, ss.CHEMISTRY_COURSE, ss.INFORMATICS_COURSE, ss.PHYSICS_COURSE
FROM sum_scores ss JOIN APPLICANT a ON ss.APP_ID = a.ID WHERE APP_ID = 3;

SELECT DISTINCT c.COURSE_NAME, a.LASTNAME, a.FIRSTNAME, a.SECONDNAME, a.BIRTHDAY, 
CASE
	WHEN c.SUBJECT = 'CHEMISTRY'
    THEN ss.CHEMISTRY_COURSE
    WHEN c.SUBJECT = 'INFORMATICS'
    THEN ss.INFORMATICS_COURSE
    WHEN c.SUBJECT = 'PHYSICS'
    THEN ss.PHYSICS_COURSE
END SCORES
FROM APP_REQUEST ar JOIN APPLICANT a ON ar.APP_ID = a.ID 
JOIN COURSE c ON ar.COURSE_ID = c.ID 
JOIN sum_scores ss ON ar.APP_ID =  ss.APP_ID
WHERE c.ID = 1
ORDER BY SCORES DESC LIMIT 45;